"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "tl"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Expanded translations for all non-official pages
const translations = {
  en: {
    // Header & Navigation
    "nav.home": "Home",
    "nav.certificates": "Certificates",
    "nav.appointments": "Appointments",
    "nav.blotter": "Blotter Reports",
    "nav.events": "Events & Announcements",
    "nav.officials": "Elected Officials",
    "nav.services": "Services",
    "nav.community": "Community",
    "nav.manage": "Manage",
    login: "Login",
    logout: "Log out",
    profile: "Profile",
    settings: "Settings",
    notifications: "Notifications",

    // Footer
    "footer.rights": "All rights reserved.",
    "footer.about": "About",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.contact": "Contact",
    "footer.quickLinks": "Quick Links",
    "footer.legal": "Legal",
    "footer.contactUs": "Contact Us",

    // Home Page
    "home.hero.title": "Welcome to",
    "home.hero.subtitle":
      "Your one-stop platform for all barangay services. Request certificates, schedule appointments, and submit reports with ease.",
    "home.hero.getStarted": "Get Started",
    "home.hero.learnMore": "Learn More",

    // Services Section
    "services.title": "Our Services",
    "services.subtitle": "Digital Barangay Services",
    "services.description": "Access a wide range of barangay services online, anytime, anywhere.",

    "services.certificates.title": "Certificate Requests",
    "services.certificates.description": "Request barangay certificates, clearances, and other documents online.",
    "services.certificates.benefit": "Skip the long lines and get your documents processed faster.",
    "services.certificates.cta": "Request Now",

    "services.appointments.title": "Appointment Scheduling",
    "services.appointments.description": "Schedule appointments with barangay officials and services.",
    "services.appointments.benefit": "Book your preferred date and time without the hassle of waiting.",
    "services.appointments.cta": "Schedule Now",

    "services.blotter.title": "Blotter Reports",
    "services.blotter.description": "File incident reports and complaints online.",
    "services.blotter.benefit": "Report incidents quickly and track the status of your reports.",
    "services.blotter.cta": "File Report",

    // How It Works Section
    "howItWorks.title": "Simple Process",
    "howItWorks.subtitle": "How It Works",
    "howItWorks.description": "Simple steps to access barangay services online.",
    "howItWorks.step1.title": "Create an Account",
    "howItWorks.step1.description": "Register with your personal details to access all services.",
    "howItWorks.step2.title": "Select a Service",
    "howItWorks.step2.description": "Choose from certificate requests, appointments, or blotter reports.",
    "howItWorks.step3.title": "Track Your Request",
    "howItWorks.step3.description": "Monitor the status of your requests in real-time.",

    // Community Section
    "community.title": "Latest Updates",
    "community.subtitle": "Community Highlights",
    "community.description": "Stay updated with the latest news and events in your barangay.",
    "community.events.title": "Upcoming Community Events",
    "community.events.description": "Join us for these upcoming activities",
    "community.events.viewAll": "View All Events",
    "community.announcements.title": "Latest Announcements",
    "community.announcements.description": "Important updates from your barangay",
    "community.announcements.viewAll": "View All Announcements",

    // CTA Section
    "cta.title": "Ready to Get Started?",
    "cta.description": "Join thousands of residents who are already using Barangay Connect to access services online.",
    "cta.requestCertificate": "Request a Certificate",
    "cta.scheduleAppointment": "Schedule an Appointment",

    // Certificates Page
    "certificates.title": "Certificate Requests",
    "certificates.description": "Request and track your barangay certificates and documents.",
    "certificates.request": "Request Certificate",
    "certificates.track": "Track Requests",
    "certificates.barangayClearance": "Barangay Clearance",
    "certificates.residency": "Certificate of Residency",
    "certificates.indigency": "Indigency Certificate",
    "certificates.processing": "Processing time",
    "certificates.requiredFor": "Required for",
    "certificates.requestNow": "Request Now",
    "certificates.yourRequests": "Your Certificate Requests",
    "certificates.trackStatus": "Track the status of your certificate requests.",
    "certificates.reference": "Reference #",
    "certificates.requestedOn": "Requested on",
    "certificates.status.processing": "Processing",
    "certificates.status.ready": "Ready for Pickup",
    "certificates.status.additionalInfo": "Additional Info Required",

    // Appointments Page
    "appointments.title": "Appointments",
    "appointments.description": "Schedule and manage your appointments with barangay officials.",
    "appointments.schedule": "Schedule Appointment",
    "appointments.manage": "Manage Appointments",
    "appointments.newAppointment": "Schedule a New Appointment",
    "appointments.chooseService": "Choose a service, date, and time for your appointment.",
    "appointments.serviceType": "Service Type",
    "appointments.date": "Date",
    "appointments.time": "Time",
    "appointments.purpose": "Purpose of Appointment",
    "appointments.scheduleButton": "Schedule Appointment",
    "appointments.yourAppointments": "Your Appointments",
    "appointments.viewManage": "View and manage your scheduled appointments.",
    "appointments.status.confirmed": "Confirmed",
    "appointments.status.pending": "Pending",
    "appointments.status.cancelled": "Cancelled",
    "appointments.reschedule": "Reschedule",
    "appointments.cancel": "Cancel",

    // Blotter Page
    "blotter.title": "Blotter Reports",
    "blotter.description": "File and track incident reports and complaints.",
    "blotter.file": "File a Report",
    "blotter.track": "Track Reports",
    "blotter.newReport": "File a New Blotter Report",
    "blotter.provideDetails": "Provide details about the incident or complaint.",
    "blotter.incidentType": "Incident Type",
    "blotter.incidentDate": "Incident Date",
    "blotter.incidentTime": "Incident Time",
    "blotter.incidentLocation": "Incident Location",
    "blotter.incidentDescription": "Incident Description",
    "blotter.personsInvolved": "Persons Involved",
    "blotter.evidenceUpload": "Evidence Upload",
    "blotter.submitReport": "Submit Report",
    "blotter.yourReports": "Your Blotter Reports",
    "blotter.trackStatus": "Track the status of your filed reports.",
    "blotter.status.pending": "Pending Review",
    "blotter.status.investigating": "Under Investigation",
    "blotter.status.resolved": "Resolved",
    "blotter.viewDetails": "View Details",

    // Login Form
    "login.title": "Login to your account",
    "login.description": "Enter your credentials to access your barangay services.",
    "login.email": "Email",
    "login.password": "Password",
    "login.forgotPassword": "Forgot password?",
    "login.loginButton": "Login",
    "login.registerPrompt": "Don't have an account?",
    "login.registerLink": "Register here",
    "login.resident": "Resident",
    "login.official": "Barangay Official",
    "login.residentEmail": "Email",
    "login.officialEmail": "Official Email",
    "login.loggingIn": "Logging in...",
    "login.asResident": "Login as Resident",
    "login.asOfficial": "Login as Official",

    // Events and Announcements Page
    "events.title": "Events & Announcements",
    "events.description": "Stay updated with the latest happenings in our barangay.",
    "events.upcoming": "Upcoming Events",
    "events.past": "Past Events",
    "events.announcements": "Important Announcements",
    "events.date": "Date",
    "events.time": "Time",
    "events.location": "Location",
    "events.organizer": "Organizer",
    "events.contact": "Contact",
    "events.details": "Event Details",
    "events.register": "Register for Event",
    "events.viewMore": "View More",
    "events.noEvents": "No upcoming events at this time.",
    "events.filterBy": "Filter by",
    "events.searchEvents": "Search events...",
    "events.category": "Category",
    "events.allCategories": "All Categories",
    "events.community": "Community",
    "events.health": "Health",
    "events.education": "Education",
    "events.sports": "Sports",
    "events.culture": "Culture",
    "events.government": "Government",
    "events.postedOn": "Posted on",
    "events.readMore": "Read More",
    "events.shareEvent": "Share Event",

    // Elected Officials Page
    "officials.title": "Elected Officials",
    "officials.description": "Meet the dedicated leaders serving our barangay.",
    "officials.currentTerm": "Current Term",
    "officials.contactInfo": "Contact Information",
    "officials.email": "Email",
    "officials.phone": "Phone",
    "officials.office": "Office Hours",
    "officials.biography": "Biography",
    "officials.projects": "Key Projects",
    "officials.achievements": "Achievements",
    "officials.messageTitle": "Message from the",
    "officials.captain": "Barangay Captain",
    "officials.councilors": "Barangay Councilors",
    "officials.secretary": "Barangay Secretary",
    "officials.treasurer": "Barangay Treasurer",
    "officials.skChairperson": "SK Chairperson",
    "officials.committees": "Committees",
    "officials.scheduleAppointment": "Schedule an Appointment",
    "officials.viewProfile": "View Full Profile",

    // Home page sections for new pages
    "home.events.title": "Upcoming Events",
    "home.events.subtitle": "Join Our Community Activities",
    "home.events.description": "Stay informed about upcoming events and important announcements in our barangay.",
    "home.events.viewAll": "View All Events & Announcements",

    "home.officials.title": "Your Barangay Leaders",
    "home.officials.subtitle": "Meet Our Elected Officials",
    "home.officials.description": "Get to know the dedicated public servants working for our community's development.",
    "home.officials.viewAll": "View All Officials",
    "home.officials.message": "Message from the Barangay Captain",

    // Admin Management
    "admin.dashboard": "Admin Dashboard",
    "admin.manage": "Manage",
    "admin.events": "Events",
    "admin.officials": "Officials",
    "admin.announcements": "Announcements",
    "admin.certificates": "Certificates",
    "admin.appointments": "Appointments",
    "admin.blotter": "Blotter Reports",
    "admin.residents": "Residents",
    "admin.settings": "Settings",

    // Events Management
    "admin.events.title": "Events Management",
    "admin.events.description": "Create, update, and manage barangay events.",
    "admin.events.add": "Add New Event",
    "admin.events.edit": "Edit Event",
    "admin.events.delete": "Delete Event",
    "admin.events.view": "View Event Details",
    "admin.events.list": "Events List",
    "admin.events.eventName": "Event Name",
    "admin.events.eventDate": "Event Date",
    "admin.events.eventTime": "Event Time",
    "admin.events.eventLocation": "Event Location",
    "admin.events.eventDescription": "Event Description",
    "admin.events.eventCategory": "Event Category",
    "admin.events.eventOrganizer": "Event Organizer",
    "admin.events.eventContact": "Contact Person",
    "admin.events.eventImage": "Event Image",
    "admin.events.uploadImage": "Upload Image",
    "admin.events.save": "Save Event",
    "admin.events.cancel": "Cancel",
    "admin.events.confirmDelete": "Are you sure you want to delete this event?",
    "admin.events.deleteSuccess": "Event deleted successfully",
    "admin.events.saveSuccess": "Event saved successfully",
    "admin.events.updateSuccess": "Event updated successfully",
    "admin.events.status": "Status",
    "admin.events.active": "Active",
    "admin.events.inactive": "Inactive",
    "admin.events.featured": "Featured",
    "admin.events.registrations": "Registrations",
    "admin.events.viewRegistrations": "View Registrations",
    "admin.events.noRegistrations": "No registrations for this event yet.",
    "admin.events.searchPlaceholder": "Search events...",
    "admin.events.filterByCategory": "Filter by category",
    "admin.events.filterByStatus": "Filter by status",
    "admin.events.sortBy": "Sort by",
    "admin.events.dateAsc": "Date (Oldest first)",
    "admin.events.dateDesc": "Date (Newest first)",
    "admin.events.nameAsc": "Name (A-Z)",
    "admin.events.nameDesc": "Name (Z-A)",

    // Officials Management
    "admin.officials.title": "Officials Management",
    "admin.officials.description": "Add, edit, and manage barangay officials information.",
    "admin.officials.add": "Add New Official",
    "admin.officials.edit": "Edit Official",
    "admin.officials.delete": "Delete Official",
    "admin.officials.view": "View Official Details",
    "admin.officials.list": "Officials List",
    "admin.officials.name": "Name",
    "admin.officials.position": "Position",
    "admin.officials.term": "Term",
    "admin.officials.email": "Email",
    "admin.officials.phone": "Phone",
    "admin.officials.officeHours": "Office Hours",
    "admin.officials.committees": "Committees",
    "admin.officials.biography": "Biography",
    "admin.officials.photo": "Photo",
    "admin.officials.uploadPhoto": "Upload Photo",
    "admin.officials.save": "Save Official",
    "admin.officials.cancel": "Cancel",
    "admin.officials.confirmDelete": "Are you sure you want to delete this official?",
    "admin.officials.deleteSuccess": "Official deleted successfully",
    "admin.officials.saveSuccess": "Official saved successfully",
    "admin.officials.updateSuccess": "Official updated successfully",
    "admin.officials.status": "Status",
    "admin.officials.active": "Active",
    "admin.officials.inactive": "Inactive",
    "admin.officials.searchPlaceholder": "Search officials...",
    "admin.officials.filterByPosition": "Filter by position",
    "admin.officials.filterByStatus": "Filter by status",
    "admin.officials.sortBy": "Sort by",
    "admin.officials.positionAsc": "Position (A-Z)",
    "admin.officials.positionDesc": "Position (Z-A)",
    "admin.officials.nameAsc": "Name (A-Z)",
    "admin.officials.nameDesc": "Name (Z-A)",
    "admin.officials.message": "Message",
    "admin.officials.projects": "Key Projects",
    "admin.officials.achievements": "Achievements",
    "admin.officials.addCommittee": "Add Committee",
    "admin.officials.removeCommittee": "Remove",

    // Announcements Management
    "admin.announcements.title": "Announcements Management",
    "admin.announcements.description": "Create, update, and manage barangay announcements.",
    "admin.announcements.add": "Add New Announcement",
    "admin.announcements.edit": "Edit Announcement",
    "admin.announcements.delete": "Delete Announcement",
    "admin.announcements.view": "View Announcement Details",
    "admin.announcements.list": "Announcements List",
    "admin.announcements.announcementTitle": "Announcement Title",
    "admin.announcements.announcementDate": "Date Posted",
    "admin.announcements.announcementContent": "Content",
    "admin.announcements.announcementCategory": "Category",
    "admin.announcements.announcementPriority": "Priority",
    "admin.announcements.save": "Save Announcement",
    "admin.announcements.cancel": "Cancel",
    "admin.announcements.confirmDelete": "Are you sure you want to delete this announcement?",
    "admin.announcements.deleteSuccess": "Announcement deleted successfully",
    "admin.announcements.saveSuccess": "Announcement saved successfully",
    "admin.announcements.updateSuccess": "Announcement updated successfully",
    "admin.announcements.status": "Status",
    "admin.announcements.active": "Active",
    "admin.announcements.inactive": "Inactive",
    "admin.announcements.searchPlaceholder": "Search announcements...",
    "admin.announcements.filterByCategory": "Filter by category",
    "admin.announcements.filterByPriority": "Filter by priority",
    "admin.announcements.sortBy": "Sort by",
    "admin.announcements.dateAsc": "Date (Oldest first)",
    "admin.announcements.dateDesc": "Date (Newest first)",
    "admin.announcements.titleAsc": "Title (A-Z)",
    "admin.announcements.titleDesc": "Title (Z-A)",
    "admin.announcements.priority.low": "Low",
    "admin.announcements.priority.medium": "Medium",
    "admin.announcements.priority.high": "High",
    "admin.announcements.priority.urgent": "Urgent",

    // Common Admin UI
    "admin.actions": "Actions",
    "admin.search": "Search",
    "admin.filter": "Filter",
    "admin.sort": "Sort",
    "admin.add": "Add New",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.view": "View",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.confirm": "Confirm",
    "admin.back": "Back",
    "admin.next": "Next",
    "admin.previous": "Previous",
    "admin.loading": "Loading...",
    "admin.noData": "No data available",
    "admin.required": "Required",
    "admin.optional": "Optional",
    "admin.success": "Success",
    "admin.error": "Error",
    "admin.warning": "Warning",
    "admin.info": "Information",

    // Language selector
    language: "Language",
    "language.english": "English",
    "language.tagalog": "Tagalog",
  },
  tl: {
    // Header & Navigation
    "nav.home": "Tahanan",
    "nav.certificates": "Mga Sertipiko",
    "nav.appointments": "Mga Appointment",
    "nav.blotter": "Mga Ulat ng Blotter",
    "nav.events": "Mga Kaganapan at Anunsyo",
    "nav.officials": "Mga Nahalal na Opisyal",
    "nav.services": "Mga Serbisyo",
    "nav.community": "Komunidad",
    "nav.manage": "Pangasiwaan",
    login: "Mag-login",
    logout: "Mag-logout",
    profile: "Profile",
    settings: "Mga Setting",
    notifications: "Mga Abiso",

    // Footer
    "footer.rights": "Nakalaan ang lahat ng karapatan.",
    "footer.about": "Tungkol sa Amin",
    "footer.privacy": "Patakaran sa Privacy",
    "footer.terms": "Mga Tuntunin",
    "footer.contact": "Makipag-ugnayan",
    "footer.quickLinks": "Mga Mabilis na Link",
    "footer.legal": "Legal",
    "footer.contactUs": "Makipag-ugnayan sa Amin",

    // Home Page
    "home.hero.title": "Maligayang pagdating sa",
    "home.hero.subtitle":
      "Ang iyong one-stop platform para sa lahat ng serbisyo ng barangay. Humiling ng mga sertipiko, mag-iskedyul ng mga appointment, at magsumite ng mga ulat nang madali.",
    "home.hero.getStarted": "Magsimula",
    "home.hero.learnMore": "Matuto pa",

    // Services Section
    "services.title": "Aming Mga Serbisyo",
    "services.subtitle": "Mga Digital na Serbisyo ng Barangay",
    "services.description": "I-access ang malawak na hanay ng mga serbisyo ng barangay online, anumang oras, saanman.",

    "services.certificates.title": "Mga Kahilingan ng Sertipiko",
    "services.certificates.description":
      "Humiling ng mga sertipiko, clearance, at iba pang dokumento ng barangay online.",
    "services.certificates.benefit":
      "Laktawan ang mahabang pila at maproseso ang iyong mga dokumento nang mas mabilis.",
    "services.certificates.cta": "Humiling Ngayon",

    "services.appointments.title": "Pag-iskedyul ng Appointment",
    "services.appointments.description": "Mag-iskedyul ng mga appointment sa mga opisyal at serbisyo ng barangay.",
    "services.appointments.benefit": "I-book ang iyong gustong petsa at oras nang walang abala ng paghihintay.",
    "services.appointments.cta": "Mag-iskedyul Ngayon",

    "services.blotter.title": "Mga Ulat ng Blotter",
    "services.blotter.description": "Mag-file ng mga ulat ng insidente at reklamo online.",
    "services.blotter.benefit": "Mag-ulat ng mga insidente nang mabilis at subaybayan ang status ng iyong mga ulat.",
    "services.blotter.cta": "Mag-file ng Ulat",

    // How It Works Section
    "howItWorks.title": "Simpleng Proseso",
    "howItWorks.subtitle": "Paano Ito Gumagana",
    "howItWorks.description": "Simpleng hakbang para ma-access ang mga serbisyo ng barangay online.",
    "howItWorks.step1.title": "Gumawa ng Account",
    "howItWorks.step1.description":
      "Magparehistro gamit ang iyong personal na detalye para ma-access ang lahat ng serbisyo.",
    "howItWorks.step2.title": "Pumili ng Serbisyo",
    "howItWorks.step2.description": "Pumili mula sa mga kahilingan ng sertipiko, appointment, o mga ulat ng blotter.",
    "howItWorks.step3.title": "Subaybayan ang Iyong Kahilingan",
    "howItWorks.step3.description": "Subaybayan ang status ng iyong mga kahilingan sa real-time.",

    // Community Section
    "community.title": "Mga Pinakabagong Update",
    "community.subtitle": "Mga Highlight ng Komunidad",
    "community.description": "Manatiling updated sa pinakabagong balita at mga kaganapan sa iyong barangay.",
    "community.events.title": "Mga Paparating na Kaganapan sa Komunidad",
    "community.events.description": "Sumali sa amin para sa mga paparating na aktibidad",
    "community.events.viewAll": "Tingnan Lahat ng Kaganapan",
    "community.announcements.title": "Mga Pinakabagong Anunsyo",
    "community.announcements.description": "Mahahalagang update mula sa iyong barangay",
    "community.announcements.viewAll": "Tingnan Lahat ng Anunsyo",

    // CTA Section
    "cta.title": "Handa na bang Magsimula?",
    "cta.description":
      "Sumali sa libu-libong residente na gumagamit na ng Barangay Connect para ma-access ang mga serbisyo online.",
    "cta.requestCertificate": "Humiling ng Sertipiko",
    "cta.scheduleAppointment": "Mag-iskedyul ng Appointment",

    // Certificates Page
    "certificates.title": "Mga Kahilingan ng Sertipiko",
    "certificates.description": "Humiling at subaybayan ang iyong mga sertipiko at dokumento ng barangay.",
    "certificates.request": "Humiling ng Sertipiko",
    "certificates.track": "Subaybayan ang mga Kahilingan",
    "certificates.barangayClearance": "Barangay Clearance",
    "certificates.residency": "Sertipiko ng Paninirahan",
    "certificates.indigency": "Sertipiko ng Kahirapan",
    "certificates.processing": "Oras ng pagproseso",
    "certificates.requiredFor": "Kinakailangan para sa",
    "certificates.requestNow": "Humiling Ngayon",
    "certificates.yourRequests": "Ang Iyong Mga Kahilingan ng Sertipiko",
    "certificates.trackStatus": "Subaybayan ang status ng iyong mga kahilingan ng sertipiko.",
    "certificates.reference": "Reference #",
    "certificates.requestedOn": "Hiniling noong",
    "certificates.status.processing": "Pinoproseso",
    "certificates.status.ready": "Handa nang Kunin",
    "certificates.status.additionalInfo": "Kailangan ng Karagdagang Impormasyon",

    // Appointments Page
    "appointments.title": "Mga Appointment",
    "appointments.description": "Mag-iskedyul at pamahalaan ang iyong mga appointment sa mga opisyal ng barangay.",
    "appointments.schedule": "Mag-iskedyul ng Appointment",
    "appointments.manage": "Pamahalaan ang mga Appointment",
    "appointments.newAppointment": "Mag-iskedyul ng Bagong Appointment",
    "appointments.chooseService": "Pumili ng serbisyo, petsa, at oras para sa iyong appointment.",
    "appointments.serviceType": "Uri ng Serbisyo",
    "appointments.date": "Petsa",
    "appointments.time": "Oras",
    "appointments.purpose": "Layunin ng Appointment",
    "appointments.scheduleButton": "Mag-iskedyul ng Appointment",
    "appointments.yourAppointments": "Ang Iyong Mga Appointment",
    "appointments.viewManage": "Tingnan at pamahalaan ang iyong mga naka-iskedyul na appointment.",
    "appointments.status.confirmed": "Nakumpirma",
    "appointments.status.pending": "Nakabinbin",
    "appointments.status.cancelled": "Nakansela",
    "appointments.reschedule": "I-reschedule",
    "appointments.cancel": "Kanselahin",

    // Blotter Page
    "blotter.title": "Mga Ulat ng Blotter",
    "blotter.description": "Mag-file at subaybayan ang mga ulat ng insidente at reklamo.",
    "blotter.file": "Mag-file ng Ulat",
    "blotter.track": "Subaybayan ang mga Ulat",
    "blotter.newReport": "Mag-file ng Bagong Ulat ng Blotter",
    "blotter.provideDetails": "Magbigay ng mga detalye tungkol sa insidente o reklamo.",
    "blotter.incidentType": "Uri ng Insidente",
    "blotter.incidentDate": "Petsa ng Insidente",
    "blotter.incidentTime": "Oras ng Insidente",
    "blotter.incidentLocation": "Lokasyon ng Insidente",
    "blotter.incidentDescription": "Paglalarawan ng Insidente",
    "blotter.personsInvolved": "Mga Taong Kasangkot",
    "blotter.evidenceUpload": "Pag-upload ng Ebidensya",
    "blotter.submitReport": "Isumite ang Ulat",
    "blotter.yourReports": "Ang Iyong Mga Ulat ng Blotter",
    "blotter.trackStatus": "Subaybayan ang status ng iyong mga nai-file na ulat.",
    "blotter.status.pending": "Nakabinbin ang Pagsusuri",
    "blotter.status.investigating": "Iniimbestigahan",
    "blotter.status.resolved": "Nalutas",
    "blotter.viewDetails": "Tingnan ang mga Detalye",

    // Login Form
    "login.title": "Mag-login sa iyong account",
    "login.description": "Ilagay ang iyong mga kredensyal para ma-access ang mga serbisyo ng barangay.",
    "login.email": "Email",
    "login.password": "Password",
    "login.forgotPassword": "Nakalimutan ang password?",
    "login.loginButton": "Mag-login",
    "login.registerPrompt": "Wala pang account?",
    "login.registerLink": "Magparehistro dito",
    "login.resident": "Residente",
    "login.official": "Opisyal ng Barangay",
    "login.residentEmail": "Email",
    "login.officialEmail": "Email ng Opisyal",
    "login.loggingIn": "Naglo-login...",
    "login.asResident": "Mag-login bilang Residente",
    "login.asOfficial": "Mag-login bilang Opisyal",

    // Events and Announcements Page
    "events.title": "Mga Kaganapan at Anunsyo",
    "events.description": "Manatiling updated sa mga pinakabagong pangyayari sa ating barangay.",
    "events.upcoming": "Mga Paparating na Kaganapan",
    "events.past": "Mga Nakaraang Kaganapan",
    "events.announcements": "Mahahalagang Anunsyo",
    "events.date": "Petsa",
    "events.time": "Oras",
    "events.location": "Lokasyon",
    "events.organizer": "Tagapag-organisa",
    "events.contact": "Kontak",
    "events.details": "Mga Detalye ng Kaganapan",
    "events.register": "Magparehistro para sa Kaganapan",
    "events.viewMore": "Tingnan pa",
    "events.noEvents": "Walang paparating na kaganapan sa ngayon.",
    "events.filterBy": "I-filter ayon sa",
    "events.searchEvents": "Maghanap ng mga kaganapan...",
    "events.category": "Kategorya",
    "events.allCategories": "Lahat ng Kategorya",
    "events.community": "Komunidad",
    "events.health": "Kalusugan",
    "events.education": "Edukasyon",
    "events.sports": "Palakasan",
    "events.culture": "Kultura",
    "events.government": "Gobyerno",
    "events.postedOn": "Nai-post noong",
    "events.readMore": "Magbasa pa",
    "events.shareEvent": "Ibahagi ang Kaganapan",

    // Elected Officials Page
    "officials.title": "Mga Nahalal na Opisyal",
    "officials.description": "Kilalanin ang mga dedikadong lider na naglilingkod sa ating barangay.",
    "officials.currentTerm": "Kasalukuyang Termino",
    "officials.contactInfo": "Impormasyon sa Pakikipag-ugnayan",
    "officials.email": "Email",
    "officials.phone": "Telepono",
    "officials.office": "Oras ng Opisina",
    "officials.biography": "Talambuhay",
    "officials.projects": "Mga Pangunahing Proyekto",
    "officials.achievements": "Mga Nagawa",
    "officials.messageTitle": "Mensahe mula sa",
    "officials.captain": "Punong Barangay",
    "officials.councilors": "Mga Kagawad ng Barangay",
    "officials.secretary": "Kalihim ng Barangay",
    "officials.treasurer": "Ingat-Yaman ng Barangay",
    "officials.skChairperson": "Tagapangulo ng SK",
    "officials.committees": "Mga Komite",
    "officials.scheduleAppointment": "Mag-iskedyul ng Appointment",
    "officials.viewProfile": "Tingnan ang Buong Profile",

    // Home page sections for new pages
    "home.events.title": "Mga Paparating na Kaganapan",
    "home.events.subtitle": "Sumali sa Mga Aktibidad ng Ating Komunidad",
    "home.events.description":
      "Manatiling updated sa mga paparating na kaganapan at mahahalagang anunsyo sa ating barangay.",
    "home.events.viewAll": "Tingnan Lahat ng Kaganapan at Anunsyo",

    "home.officials.title": "Ang Inyong mga Lider sa Barangay",
    "home.officials.subtitle": "Kilalanin ang Ating mga Nahalal na Opisyal",
    "home.officials.description":
      "Kilalanin ang mga dedikadong lingkod-bayan na nagtatrabaho para sa pag-unlad ng ating komunidad.",
    "home.officials.viewAll": "Tingnan Lahat ng mga Opisyal",
    "home.officials.message": "Mensahe mula sa Punong Barangay",

    // Admin Management
    "admin.dashboard": "Dashboard ng Admin",
    "admin.manage": "Pangasiwaan",
    "admin.events": "Mga Kaganapan",
    "admin.officials": "Mga Opisyal",
    "admin.announcements": "Mga Anunsyo",
    "admin.certificates": "Mga Sertipiko",
    "admin.appointments": "Mga Appointment",
    "admin.blotter": "Mga Ulat ng Blotter",
    "admin.residents": "Mga Residente",
    "admin.settings": "Mga Setting",

    // Events Management
    "admin.events.title": "Pamamahala ng Mga Kaganapan",
    "admin.events.description": "Lumikha, mag-update, at pamahalaan ang mga kaganapan sa barangay.",
    "admin.events.add": "Magdagdag ng Bagong Kaganapan",
    "admin.events.edit": "I-edit ang Kaganapan",
    "admin.events.delete": "Burahin ang Kaganapan",
    "admin.events.view": "Tingnan ang Mga Detalye ng Kaganapan",
    "admin.events.list": "Listahan ng Mga Kaganapan",
    "admin.events.eventName": "Pangalan ng Kaganapan",
    "admin.events.eventDate": "Petsa ng Kaganapan",
    "admin.events.eventTime": "Oras ng Kaganapan",
    "admin.events.eventLocation": "Lokasyon ng Kaganapan",
    "admin.events.eventDescription": "Paglalarawan ng Kaganapan",
    "admin.events.eventCategory": "Kategorya ng Kaganapan",
    "admin.events.eventOrganizer": "Tagapag-organisa ng Kaganapan",
    "admin.events.eventContact": "Taong Maaaring Tawagan",
    "admin.events.eventImage": "Larawan ng Kaganapan",
    "admin.events.uploadImage": "Mag-upload ng Larawan",
    "admin.events.save": "I-save ang Kaganapan",
    "admin.events.cancel": "Kanselahin",
    "admin.events.confirmDelete": "Sigurado ka bang gusto mong burahin ang kaganapang ito?",
    "admin.events.deleteSuccess": "Matagumpay na nabura ang kaganapan",
    "admin.events.saveSuccess": "Matagumpay na na-save ang kaganapan",
    "admin.events.updateSuccess": "Matagumpay na na-update ang kaganapan",
    "admin.events.status": "Katayuan",
    "admin.events.active": "Aktibo",
    "admin.events.inactive": "Hindi Aktibo",
    "admin.events.featured": "Tampok",
    "admin.events.registrations": "Mga Rehistrasyon",
    "admin.events.viewRegistrations": "Tingnan ang Mga Rehistrasyon",
    "admin.events.noRegistrations": "Wala pang rehistrasyon para sa kaganapang ito.",
    "admin.events.searchPlaceholder": "Maghanap ng mga kaganapan...",
    "admin.events.filterByCategory": "I-filter ayon sa kategorya",
    "admin.events.filterByStatus": "I-filter ayon sa katayuan",
    "admin.events.sortBy": "Ayusin ayon sa",
    "admin.events.dateAsc": "Petsa (Pinakaluma muna)",
    "admin.events.dateDesc": "Petsa (Pinakabago muna)",
    "admin.events.nameAsc": "Pangalan (A-Z)",
    "admin.events.nameDesc": "Pangalan (Z-A)",

    // Officials Management
    "admin.officials.title": "Pamamahala ng Mga Opisyal",
    "admin.officials.description": "Magdagdag, mag-edit, at pamahalaan ang impormasyon ng mga opisyal ng barangay.",
    "admin.officials.add": "Magdagdag ng Bagong Opisyal",
    "admin.officials.edit": "I-edit ang Opisyal",
    "admin.officials.delete": "Burahin ang Opisyal",
    "admin.officials.view": "Tingnan ang Mga Detalye ng Opisyal",
    "admin.officials.list": "Listahan ng Mga Opisyal",
    "admin.officials.name": "Pangalan",
    "admin.officials.position": "Posisyon",
    "admin.officials.term": "Termino",
    "admin.officials.email": "Email",
    "admin.officials.phone": "Telepono",
    "admin.officials.officeHours": "Oras ng Opisina",
    "admin.officials.committees": "Mga Komite",
    "admin.officials.biography": "Talambuhay",
    "admin.officials.photo": "Larawan",
    "admin.officials.uploadPhoto": "Mag-upload ng Larawan",
    "admin.officials.save": "I-save ang Opisyal",
    "admin.officials.cancel": "Kanselahin",
    "admin.officials.confirmDelete": "Sigurado ka bang gusto mong burahin ang opisyal na ito?",
    "admin.officials.deleteSuccess": "Matagumpay na nabura ang opisyal",
    "admin.officials.saveSuccess": "Matagumpay na na-save ang opisyal",
    "admin.officials.updateSuccess": "Matagumpay na na-update ang opisyal",
    "admin.officials.status": "Katayuan",
    "admin.officials.active": "Aktibo",
    "admin.officials.inactive": "Hindi Aktibo",
    "admin.officials.searchPlaceholder": "Maghanap ng mga opisyal...",
    "admin.officials.filterByPosition": "I-filter ayon sa posisyon",
    "admin.officials.filterByStatus": "I-filter ayon sa katayuan",
    "admin.officials.sortBy": "Ayusin ayon sa",
    "admin.officials.positionAsc": "Posisyon (A-Z)",
    "admin.officials.positionDesc": "Posisyon (Z-A)",
    "admin.officials.nameAsc": "Pangalan (A-Z)",
    "admin.officials.nameDesc": "Pangalan (Z-A)",
    "admin.officials.message": "Mensahe",
    "admin.officials.projects": "Mga Pangunahing Proyekto",
    "admin.officials.achievements": "Mga Nagawa",
    "admin.officials.addCommittee": "Magdagdag ng Komite",
    "admin.officials.removeCommittee": "Alisin",

    // Announcements Management
    "admin.announcements.title": "Pamamahala ng Mga Anunsyo",
    "admin.announcements.description": "Lumikha, mag-update, at pamahalaan ang mga anunsyo ng barangay.",
    "admin.announcements.add": "Magdagdag ng Bagong Anunsyo",
    "admin.announcements.edit": "I-edit ang Anunsyo",
    "admin.announcements.delete": "Burahin ang Anunsyo",
    "admin.announcements.view": "Tingnan ang Mga Detalye ng Anunsyo",
    "admin.announcements.list": "Listahan ng Mga Anunsyo",
    "admin.announcements.announcementTitle": "Pamagat ng Anunsyo",
    "admin.announcements.announcementDate": "Petsa ng Pag-post",
    "admin.announcements.announcementContent": "Nilalaman",
    "admin.announcements.announcementCategory": "Kategorya",
    "admin.announcements.announcementPriority": "Priyoridad",
    "admin.announcements.save": "I-save ang Anunsyo",
    "admin.announcements.cancel": "Kanselahin",
    "admin.announcements.confirmDelete": "Sigurado ka bang gusto mong burahin ang anunsyong ito?",
    "admin.announcements.deleteSuccess": "Matagumpay na nabura ang anunsyo",
    "admin.announcements.saveSuccess": "Matagumpay na na-save ang anunsyo",
    "admin.announcements.updateSuccess": "Matagumpay na na-update ang anunsyo",
    "admin.announcements.status": "Katayuan",
    "admin.announcements.active": "Aktibo",
    "admin.announcements.inactive": "Hindi Aktibo",
    "admin.announcements.searchPlaceholder": "Maghanap ng mga anunsyo...",
    "admin.announcements.filterByCategory": "I-filter ayon sa kategorya",
    "admin.announcements.filterByPriority": "I-filter ayon sa priyoridad",
    "admin.announcements.sortBy": "Ayusin ayon sa",
    "admin.announcements.dateAsc": "Petsa (Pinakaluma muna)",
    "admin.announcements.dateDesc": "Petsa (Pinakabago muna)",
    "admin.announcements.titleAsc": "Pamagat (A-Z)",
    "admin.announcements.titleDesc": "Pamagat (Z-A)",
    "admin.announcements.priority.low": "Mababa",
    "admin.announcements.priority.medium": "Katamtaman",
    "admin.announcements.priority.high": "Mataas",
    "admin.announcements.priority.urgent": "Agaran",

    // Common Admin UI
    "admin.actions": "Mga Aksyon",
    "admin.search": "Maghanap",
    "admin.filter": "I-filter",
    "admin.sort": "Ayusin",
    "admin.add": "Magdagdag ng Bago",
    "admin.edit": "I-edit",
    "admin.delete": "Burahin",
    "admin.view": "Tingnan",
    "admin.save": "I-save",
    "admin.cancel": "Kanselahin",
    "admin.confirm": "Kumpirmahin",
    "admin.back": "Bumalik",
    "admin.next": "Susunod",
    "admin.previous": "Nakaraan",
    "admin.loading": "Naglo-load...",
    "admin.noData": "Walang available na data",
    "admin.required": "Kinakailangan",
    "admin.optional": "Opsyonal",
    "admin.success": "Tagumpay",
    "admin.error": "Error",
    "admin.warning": "Babala",
    "admin.info": "Impormasyon",

    // Language selector
    language: "Wika",
    "language.english": "Ingles",
    "language.tagalog": "Tagalog",
  },
}

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>("en")

  // Load saved language preference from localStorage on component mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "tl")) {
      setLanguageState(savedLanguage)
    }
  }, [])

  // Save language preference to localStorage when it changes
  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
